# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploy API

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: prod-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build package
        run: git archive --format=tar.gz -o release.tgz HEAD

      # Decodifica la clave SSH y la guarda como variable de entorno
      - name: Decode SSH key
        shell: bash
        env:
          SSH_KEY_B64: ${{ secrets.SSH_KEY_B64 }}
        run: |
          set -e
          # Decodificamos y guardamos como variable de entorno
          SSH_KEY_DECODED=$(echo "$SSH_KEY_B64" | base64 -d)
          echo "SSH_KEY_DECODED<<EOF" >> $GITHUB_ENV
          echo "$SSH_KEY_DECODED" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Normalize host/user/port (trim)
        shell: bash
        run: |
          H="$(printf '%s' "${{ secrets.SSH_HOST }}" | tr -d '\r\n\t ' )"
          U="$(printf '%s' "${{ secrets.SSH_USER }}" | tr -d '\r\n\t ' )"
          P="$(printf '%s' "${{ secrets.SSH_PORT }}" | tr -d '\r\n\t ' )"
          echo "SSH_HOST_NORM=$H" >> "$GITHUB_ENV"
          echo "SSH_USER_NORM=$U" >> "$GITHUB_ENV"
          echo "SSH_PORT_NORM=$P" >> "$GITHUB_ENV"

      - name: Upload to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.SSH_HOST_NORM }}
          username: ${{ env.SSH_USER_NORM }}
          port: ${{ env.SSH_PORT_NORM }}
          key: ${{ env.SSH_KEY_DECODED }}    # ← Cambiado: usar 'key' con el contenido
          source: "release.tgz"
          target: "/tmp"
          debug: true

      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.3
        env:
          APP_DIR: /opt/tomboy-api
        with:
          host: ${{ env.SSH_HOST_NORM }}
          username: ${{ env.SSH_USER_NORM }}
          port: ${{ env.SSH_PORT_NORM }}
          key: ${{ env.SSH_KEY_DECODED }}    # ← Cambiado: usar 'key' con el contenido
          script: |
            set -e
            REL=/tmp/release.tgz
            APP_DIR=${APP_DIR:-/opt/tomboy-api}

            sudo install -d -o www-data -g www-data "$APP_DIR"
            sudo find "$APP_DIR" -mindepth 1 -maxdepth 1 ! -name '.venv' ! -name '.env' -exec rm -rf {} +

            sudo tar --no-same-owner -xzf "$REL" -C "$APP_DIR"
            sudo chown -R www-data:www-data "$APP_DIR"

            if [ ! -d "$APP_DIR/.venv" ]; then
              sudo -u www-data python3 -m venv "$APP_DIR/.venv"
            fi
            sudo -u www-data bash -lc "
              . $APP_DIR/.venv/bin/activate &&
              python -m pip install -U pip wheel setuptools &&
              [ -f $APP_DIR/requirements.txt ] && pip install -r $APP_DIR/requirements.txt || true &&
              python -m pip install 'uvicorn[standard]' fastapi
            "

            sudo systemctl restart tomboy-api
            sudo systemctl is-active tomboy-api

      - name: Smoke test
        run: curl -fsS https://api.breathandbravery.com/docs >/dev/null