# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploy API

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: prod-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build package
        run: git archive --format=tar.gz -o release.tgz HEAD

      # Escribe la clave privada desde el Secret (Base64 → archivo)
      - name: Write SSH key to file (base64 decode)
        shell: bash
        env:
          SSH_KEY_B64: ${{ secrets.SSH_KEY_B64 }}
        run: |
          umask 077
          # decodifica a archivo
          echo "$SSH_KEY_B64" | base64 -d > "$RUNNER_TEMP/ssh_key"
          chmod 600 "$RUNNER_TEMP/ssh_key"
          # sanity checks
          ls -l "$RUNNER_TEMP/ssh_key"
          head -c 14 "$RUNNER_TEMP/ssh_key" | hexdump -C

      # Verifica que la llave es válida (si falla, el secreto está mal)
      - name: Show private key fingerprint (debug)
        run: ssh-keygen -lf "$RUNNER_TEMP/ssh_key"

      # Prueba de conexión SSH
      - name: SSH ping (-vvv)
        run: |
          ssh -vvv \
            -i "$RUNNER_TEMP/ssh_key" \
            -p "${{ secrets.SSH_PORT }}" \
            -o StrictHostKeyChecking=no \
            -o IdentitiesOnly=yes \
            "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" \
            'echo "SSH OK on $(hostname)"'

      # Sube el paquete al servidor
      - name: Upload to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key_path: ${{ runner.temp }}/ssh_key
          source: "release.tgz"
          target: "/tmp"
          debug: true

      # Despliegue remoto
      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.3
        env:
          APP_DIR: /opt/tomboy-api
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key_path: ${{ runner.temp }}/ssh_key
          script: |
            set -e
            REL=/tmp/release.tgz
            APP_DIR=${APP_DIR:-/opt/tomboy-api}

            sudo install -d -o www-data -g www-data "$APP_DIR"
            sudo find "$APP_DIR" -mindepth 1 -maxdepth 1 ! -name '.venv' ! -name '.env' -exec rm -rf {} +

            sudo tar --no-same-owner -xzf "$REL" -C "$APP_DIR"
            sudo chown -R www-data:www-data "$APP_DIR"

            if [ ! -d "$APP_DIR/.venv" ]; then
              sudo -u www-data python3 -m venv "$APP_DIR/.venv"
            fi
            sudo -u www-data bash -lc "
              . $APP_DIR/.venv/bin/activate &&
              python -m pip install -U pip wheel setuptools &&
              [ -f $APP_DIR/requirements.txt ] && pip install -r $APP_DIR/requirements.txt || true &&
              python -m pip install 'uvicorn[standard]' fastapi
            "

            sudo systemctl restart tomboy-api
            sudo systemctl is-active tomboy-api

      - name: Smoke test
        run: curl -fsS https://api.breathandbravery.com/docs >/dev/null